import { appColors, appRadius, appSpacing } from "../../theme/designSystem";

export const ZAKAT_UI = {
  spacing: {
    xs: appSpacing.xs,
    sm: appSpacing.sm,
    md: appSpacing.md,
    lg: appSpacing.lg,
    xl: appSpacing.xxl,
  },
  radius: {
    sm: appRadius.sm,
    md: appRadius.md,
    lg: appRadius.lg,
    pill: appRadius.pill,
  },
  colors: {
    background: appColors.background,
    surface: appColors.surface,
    surfaceMuted: "#F3F6F4",
    border: appColors.border,
    textPrimary: appColors.textPrimary,
    textSecondary: appColors.textSecondary,
    textTertiary: appColors.tabInactive,
    accent: appColors.primary,
    accentSoft: "#E7F2F0",
    badgeBg: "#EDF4F2",
    badgeText: "#1E5D57",
    success: appColors.success,
    calculationBg: "#ECF6F3",
    calculationBorder: "#C7DDD9",
    ctaBg: appColors.primary,
    ctaText: "#FFFFFF",
    shadow: "rgba(17,36,43,0.08)",
  },
  categoryAccents: {
    livestock: "#0F766E",
    "grains-fruits": "#0F5A83",
    "other-agricultural-products": "#128A62",
    "trade-commerce": "#0F766E",
    industry: "#2E7D63",
    services: "#1A6E79",
    debt: "#7A5E00",
  } as Record<string, string>,
} as const;
