export const ZAKAT_UI = {
  spacing: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 20,
    xl: 28,
  },
  radius: {
    sm: 10,
    md: 12,
    lg: 16,
    pill: 999,
  },
  colors: {
    background: "#F7FAFC",
    surface: "#FFFFFF",
    surfaceMuted: "#F1F6FB",
    border: "#D8E2EC",
    textPrimary: "#12263D",
    textSecondary: "#4B6078",
    textTertiary: "#6A7D92",
    accent: "#0F6CBD",
    accentSoft: "#E7F1FB",
    badgeBg: "#EEF5FB",
    badgeText: "#1D5F98",
    success: "#0C7A52",
    calculationBg: "#ECF6FF",
    calculationBorder: "#BCD9F2",
    ctaBg: "#0F6CBD",
    ctaText: "#FFFFFF",
    shadow: "rgba(18,38,61,0.08)",
  },
  categoryAccents: {
    livestock: "#0F766E",
    "grains-fruits": "#0F6CBD",
    "other-agricultural-products": "#128A62",
    "trade-commerce": "#0D5FA8",
    industry: "#2360C2",
    services: "#0A7DA7",
    debt: "#7A5E00",
  } as Record<string, string>,
} as const;
